### ISSUE TITLE
allow force / skip errors

### ISSUE THREAD

**Issue by adjohnson916** [mzgol/grunt-ng-annotate#21]
I get errors parsing some files. There should be a `force` option that allows it to skip errors with particular files. For now, I will just exclude bad files from the `files` listing.

**Comment by mzgol** [comment]
You can use `grunt --force someTask` and it will execute all sub-tasks even if one of them fails; it's built into Grunt.

I don't like the idea of a separate option directly in `grunt-ng-annotate` for a different `--force` than what Grunt provides... Can't you use the native one?

**Comment by adjohnson916** [comment]
@mzgol - Grunt's force option doesn't provide the granularity needed to let this option proceed through files that it has trouble with, and still operate on subsequent files.

Example:

file1.js (ok)
file2.js (unparseable by this plugin - causes subtask to fail and stop executing)
file3.js (we never reach here)

**Comment by mzgol** [comment]
Hm, from what I see I invoke `ng-annotate` on all file groups separately and I only return success or failure at the end. So if only one of your files gives you errors, files declared in other file groups should be processed correctly.

Could you share your `ngAnnotate` config?

**Comment by adjohnson916** [comment]
@mzgol - Good point, but I'm specifically referring to case of multiple files within a single group.

The reason this came up is I was running on my entire {{bower_components}} directory, but some {{jquery}} concat files weren't getting parsed correctly. I decided to just blacklist it with `!bower_components/jquery` in my files config. That works too.

**Comment by mzgol** [comment]
I see. That might be because I first concatenate the files and only then pass it through `ng-annotate`.

Maybe it's related to #22? I'll get to it soon.

**Comment by mzgol** [comment]
@adjohnson916 Can you check with the newest `grunt-ng-annotate` version?

**Comment by adjohnson916** [comment]
@mzgol - I got it working, as well as with a few older versions I've tested. It seems that {{ngAnnotate}} does proceed past individual files with errors. I'm not sure where I got that idea when I reported the issue.

**Comment by mzgol** [comment]
OK, thanks for the info.
