### ISSUE TITLE
ENOENT when running "grunt-ng-annotate": "^0.9.2"

### ISSUE THREAD

**Issue by robertdunaway** [mzgol/grunt-ng-annotate#24]
I don't know if this is a ng-annotate error specifically but all my other plugins work.  This plugin works on another development machine but I set up a new machine and it doesn't.

I'm struggling with NodeJS, NPM, and ng-annotate versions.  I'm trying my best to install the latest of each but I admit to know knowing anything about uninstalling and re-installing.  I'm stumbling through this.

When the ng-annotate task runs I get the following error: 
"Warning: Unable to write "" file (Error code: ENOENT). Use --force to continue.
Aborted due to warnings."

I've stumbled through node, npm, and plugins for several hours and I'm just not sure what to try next.

Thanks,
Bob

**Comment by mzgol** [comment]
What's your operating system, Node version, npm version?

**Comment by mzgol** [comment]
Also, please run Grunt with the `--stack` option, you'll get a stack trace which I'll need to pinpoint the issue.

**Comment by mzgol** [comment]
The task config would also help. ;)

**Comment by robertdunaway** [comment]
Thanks for the quick reply.

Windows 8.1
Node 0.12.0

NPM 2.5.1

**Comment by robertdunaway** [comment]
Running "ngAnnotate:mashupCore" (ngAnnotate) task

Warning: Unable to write "" file (Error code: ENOENT). Use --force to continue.

Error: ENOENT, no such file or directory ''

    at Error (native)

    at Object.fs.openSync (fs.js:502:18)

    at Object.fs.writeFileSync (fs.js:1103:15)

    at Object.file.write (D:\Subversion-GitHub\MashupJS\tempMashupJS\MashupSourc

e\Mashup.UI.Core\node_modules\grunt\lib\grunt\file.js:296:10)

    at runNgAnnotate (D:\Subversion-GitHub\MashupJS\tempMashupJS\MashupSource\Ma

shup.UI.Core\node_modules\grunt-ng-annotate\tasks\ng-annotate.js:178:28)

    at D:\Subversion-GitHub\MashupJS\tempMashupJS\MashupSource\Mashup.UI.Core\no

de_modules\grunt-ng-annotate\tasks\ng-annotate.js:136:22

    at Array.forEach (native)

    at Object.<anonymous> (D:\Subversion-GitHub\MashupJS\tempMashupJS\MashupSour

ce\Mashup.UI.Core\node_modules\grunt-ng-annotate\tasks\ng-annotate.js:135:24)

    at Object.<anonymous> (D:\Subversion-GitHub\MashupJS\tempMashupJS\MashupSour

ce\Mashup.UI.Core\node_modules\grunt\lib\grunt\task.js:264:15)

    at Object.thisTask.fn (D:\Subversion-GitHub\MashupJS\tempMashupJS\MashupSour

ce\Mashup.UI.Core\node_modules\grunt\lib\grunt\task.js:82:16)

 

Aborted due to warnings.

**Comment by robertdunaway** [comment]
It’s a simple config.  I commented out as much as I could just to get down to basics.

ngAnnotate: {

    options: {

        singleQuotes: true,

    },

    mashupCore: {

        files: {

            //'': ['core/**/*.js', '!core/lib/**/*', '!core/dist/**/*', '!**/*.min.js']

            '': ['apps/**/*.js', '!**/*.min.js']

        },

    }

},

**Comment by mzgol** [comment]
You're providing the destination path as an empty string, it cannot work with such a config... Please read examples from README & Grunt documentation about configuration:
http://gruntjs.com/configuring-tasks

**Comment by robertdunaway** [comment]
This used to work.  What I’m trying to do is annotate the files in place.  I don’t want a destination different than the current directory and current file name.

Make sense?

My old machine works even now with this config.  Do you have a recommendation how I can make the destination directory and file name the same as the original so that I’m not creating new files?

Thanks

**Comment by robertdunaway** [comment]
I’ll do more research.

 

Here you see I’ve configure my ngAnnotate the same as my uglify with the exception that I add “.min.js” to my minified files.  Passing “” in the dest seems to put files right back where I found them.  I know I should be concatenating files but there is a specific reason I’m trying to do things this way.

I think this is no an ngAnnotate problem but it was working and I’m not sure why.

 

ngAnnotate: {

    options: {

        singleQuotes: true,

    },

    mashupCore: {

        files: [{

            //'': ['core/**/*.js', '!core/lib/**/*', '!core/dist/**/*', '!**/*.min.js']

            //'': ['apps/**/*.js', '!**/*.min.js']

            src: ['apps/**/*.js', '!**/*.min.js'],

            dest: ''

        }],

    }

},

uglify: {

    options: {

        sourceMap: true,

    },

    dist: {

        files: [

            {

                expand: true,

                src: ['<%= distFolder %>/**/*.js', '!<%= distFolder %>**/*.min.js'],

                dest: '',

                ext: '.min.js',

                extDot: 'last'

            }

        ]

    },

**Comment by mzgol** [comment]
@robertdunaway Something like this should work:
```js
ngAnnotate: {
    options: {
        singleQuotes: true,
    },
    mashupCore: {
        files: [{
            expand: true,
            src: ['apps/**/*.js', '!**/*.min.js'],
        }],
    },
},
```
In other words, you need to use the `expand` option and not set `dest` to an empty string because then the destination path will be an empty string.

Read http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically for more details.

**Comment by mzgol** [comment]
So yeah, basically it worked for you with uglify because you used `expand: true` there and you didn't with `ngAnnotate`.

**Comment by mzgol** [comment]
In any case, I'm going on vacation so I won't be able to respond here any more soon.

**Comment by robertdunaway** [comment]
You’re exactly right.  That did the trick.  I’m new to this still.  Thanks for solving a problem that wasn’t yours.  I really appreciate it.  As I learn more I hope I can contribute in some way to ngAnnotate.
