### ISSUE TITLE
Not compatible with latest node version

### ISSUE THREAD

**Issue by phillip-haydon** [mzgol/grunt-ng-annotate#27]
The current release isn't compatible with current version of Node since the ng-annotate module is out of date. What is the ETA on an update?

**Comment by mzgol** [comment]
grunt-ng-annotate `0.9.2` (a.k.a. latest) depends on ng-annotate `~0.15.1` which matches the latest one as well. You just need to re-install it.

**Comment by mzgol** [comment]
You may also run `npm update`. Generally, this affects every single package that uses version ranges for its dependencies. If a newer dependency is released, you need to update to get it. `npm install` doesn't do it.

**Comment by phillip-haydon** [comment]
:+1: I had done update which didn't work, uninstalling/re-installing fixed it.

Thanks for the prompt reply and teaching me something new about npm :)
