### ISSUE TITLE
After migrate from ngmin to ng-annotate Less plugin crash after ng-annotate task runs 

### ISSUE THREAD

**Issue by mmadrigalac** [mzgol/grunt-ng-annotate#34]
Hi,

Currently I'm migrating a project that is using ngmin to ng-annotate.
After check the documentation I saw there should not be problem by renaming my old ngmin task to ng-annotate after proper installation was done.
However I noted Less plugin ( grunt-contrib-less ) is failing whenever ng-annotate runs in the same grunt task, it's returning this error:

Fatal error: builder is not defined
ReferenceError: builder is not defined

I've done several tests where not using ng-annotate will result in no problem for Less task to run.

Could you please help me on this?
Thanks in Advance!

**Comment by mzgol** [comment]
It's hard to go from this description, I'm not doing anything less-related so this seems weird...

It's most likely a configuration problem on your part. I'd have to see the code that triggers this error to do sth about it, thought, this report is too vague.

I'll close it for now but please comment if you have a test case that reproduces the issue. I'll reopen then.
