### ISSUE TITLE
Aliases injected into $inject

### ISSUE THREAD

**Issue by andrei-cacio** [mzgol/grunt-ng-annotate#36]
If there is any code after the $inject statement, `ngAnnotate` will create 2 $inject statements using the aliases for the 2nd one. 

Before ngAnnotate:

```javascript
angular
        .module('core')
        .service('models.menu', MenuModel);

    MenuModel.$inject = ['ui.alertService', 'models.users', '$q'];

    var myVar;

   function MenuModel(alerts, users, $q) {}
```

After ngAnnotate:

```javascript
angular
        .module('core')
        .service('models.menu', MenuModel);

    MenuModel.$inject = ['ui.alertService', 'models.users', '$q'];

    var myVar;

    MenuModel.$inject = ['alerts', 'users', '$q'];

   function MenuModel() {}
```

It's a really really strange behaviour, I caught it by luck. This issue ate up my whole day.

Am I the only one experiencing this?

Regards,
Andrei.

**Comment by mzgol** [comment]
Issues unrelated to file management, source maps etc. should be reported to [ng-annotate](https://github.com/olov/ng-annotate) as that's where the annotating logic lies. Thanks!
