### ISSUE TITLE
How to annotate all javascript files under a folder

### ISSUE THREAD

**Issue by bargitta** [mzgol/grunt-ng-annotate#38]
Hi, my javascript files are in different folders and subfolders. How can I config it to annotate all files in a folder, like use something "src/**/*.js"?

**Comment by mzgol** [comment]
Do you want to replace the source files? In that case the following should work:
```js
grunt.initConfig({
    ngAnnotate: {
        all: {
            files: [
                {
                    expand: true,
                    src: ['src/**/*.js'],
                    dest: '.',
                },
            ],
        },
    },
});
```

Please read http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically for more info about configuring Grunt tasks, this is not specific to `grunt-ng-annotate` in any way.

**Comment by bargitta** [comment]
thanks, it works great!
