### ISSUE TITLE
Can we ignore files in globbing?

### ISSUE THREAD

**Issue by vance** [mzgol/grunt-ng-annotate#39]
I'm trying to ignore files while globbing. I tried this but it doesn't work?
```js
'annotated.js':[ 'src/blah/**/*.js', '!src/blah/**/*.Spec.js']
```
that's the way I do it for other grunt configs. I'm trying to ignore my spec files and I don't want to put them in a separate folder because I hate looking for things.

**Comment by mzgol** [comment]
I wrapped your code in triple backticks (click "Edit" on your post to see) as otherwise the code displays incorrectly.

This seems to me that it should work. I'm not parsing the files myself in any way, I'm using the standard Grunt way of accessing files so excluded ones shouldn't be seen by grunt-ng-annotate at all. Do you have a full config + an example file for me to check?

**Comment by mzgol** [comment]
You can also edit your local copy of the task in `node_modules/grunt-ng-annotate/tasks/ng-annotate.js` and add a console log where it iterates over files (see [these lines](https://github.com/mzgol/grunt-ng-annotate/blob/c74a6954d4cbc052657a8a0eb9c93afe1349b391/tasks/ng-annotate.js#L140-L144)); excluded files shouldn't appear there.

**Comment by vance** [comment]
Thanks. So I added a log where it actually gets the files. 
   ```                
                var concatenatedSource = mapping.src.map(function (file) {
                    console.log('concatenatedSource File' , file);
                    return grunt.file.read(file);
                }).join(separator);
```
Then I realized it is a shortcoming with the grunt docs. It implies (but does not explicitly say) that exclusion patterns have to come after inclusion, literally, in the list of files. So this is not a  ng-annotate issue. Solution below for posterity and future web searches. I'll make a PR to grunt to clarify that.
http://gruntjs.com/configuring-tasks "Patterns are processed in-order, with !-prefixed matches excluding matched files from the result set. The result set is uniqued."

Finally, here's my actual config. 
```
ngAnnotate: {
            options: {
                singleQuotes: true,
            },
            app1: {
                files: {
                    'annotated.js': [
                        'views/**/*.js',
                        '!views/**/*.Spec.js', //exclude only works if you put it AFTER the include of the same dir
                        'models/**/*.js',
                    ]
                }
            }
        },
```

**Comment by mzgol** [comment]
I'm glad you figured it out. :) BTW, I think these "negation applies only to what's before" semantics will be changing in newer [glob](https://www.npmjs.com/package/glob) versions, not sure how that affects Grunt.

**Comment by rangrasjay** [comment]
Just wanted to know, Is mentioned below way is right or not to exclude one file.

`ngAnnotate: {
			dist: {
				files: [{
					expand: true,
					cwd: '.tmp/concat/scripts',
					src: ['*.js','!<%= yeoman.app %>/scripts/abc/xyz.js'],
					dest: '.tmp/concat/scripts'
				}]
			}
		},`

**Comment by mgol** [comment]
@rangrasjay Yes, this should work as long as `yeoman.app` resolves properly in your Grunt config.
